//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/.
        /// </summary>
        internal static string AccountController {
            get {
                return ResourceManager.GetString("AccountController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votes.
        /// </summary>
        internal static string CurrentVotesAction {
            get {
                return ResourceManager.GetString("CurrentVotesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details/{0}.
        /// </summary>
        internal static string DetailsAction {
            get {
                return ResourceManager.GetString("DetailsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetBlindSignature {
            get {
                return ResourceManager.GetString("GetBlindSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        internal static string GetVoteAction {
            get {
                return ResourceManager.GetString("GetVoteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home/.
        /// </summary>
        internal static string HomeController {
            get {
                return ResourceManager.GetString("HomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string LoginAction {
            get {
                return ResourceManager.GetString("LoginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        internal static string RegisterAction {
            get {
                return ResourceManager.GetString("RegisterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote/.
        /// </summary>
        internal static string VoteController {
            get {
                return ResourceManager.GetString("VoteController", resourceCulture);
            }
        }
    }
}
